let Seneca = require('seneca')
Seneca({tag: 'mediator', legacy: {meta: true}, timeout: 60000})
//  .use('zipkin-tracer', {host: 'zipkin', sampling: 1})
//  .use('statsd', {host: 'stats'})
  .use('entity')
  .use('../mediator.js')
  .listen(8025)
  .client({pin:'role:associate', host:'associate', port:8005})
  .client({pin:'role:descriptor', host:'descriptor', port:8015})
  .client({pin:'role:properties', host:'properties', port:8030})
  .client({pin:'role:reason', host:'reason', port:8035})
  .client({pin:'role:relation', host:'relation', port:8040})
