let Seneca = require('seneca')
Seneca({tag: 'mediator', timeout: 60000})
//.test('print')
  .use('entity')
  .use('../mediator.js')
  .listen(8025)
  .client({pin:'role:associate', port:8005})
  .client({pin:'role:descriptor', port:8015})
  .client({pin:'role:properties', port:8030})
  .client({pin:'role:reason', port:8035})
  .client({pin:'role:relation', port:8040})
